name: chexnet-mlmi
channels:
  - conda-forge
dependencies:
  - python = 3.7.4
  - numpy = 1.16.5
  - matplotlib = 3.1.1
  - pillow = 6.2.1
  - pandas = 0.25.0
  - scikit-image = 0.16.1
  - scikit-learn = 0.21.3
  - seaborn = 0.9.0
  - jupyterlab